[package]
name = "wordsapi-client"
version = "0.4.0"
authors = ["Pohl Longsine <pohl.longsine@gmail.com>"]

[dependencies]
reqwest = "0.8.7"
hyper = "0.11"
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.26"
