[package]
name = "wordsapi"
version = "0.6.0"
authors = ["Pohl Longsine <pohl.longsine@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.12.35"
hyper-tls = "0.3.2"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
tokio-core = "0.1.17"
log = "0.4.8"
