[package]
name = "wordsapi"
version = "0.6.0"
authors = ["Pohl Longsine <pohl.longsine@gmail.com>"]
edition = "2021"

[dependencies]
hyper = "0.12.35"
hyper-tls = "0.3.2"
serde = "1.0.147"
serde_derive = "1.0.147"
serde_json = "1.0.87"
tokio-core = "0.1.18"
log = "0.4.17"
