[package]
name = "wordsapi-client"
version = "0.4.0"
authors = ["Pohl Longsine <pohl.longsine@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.8"
serde = "1.0.74"
serde_derive = "1.0.74"
serde_json = "1.0.26"
tokio-core = "0.1"