[package]
name = "wordsapi"
version = "0.5.0"
authors = ["Pohl Longsine <pohl.longsine@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12"
hyper-tls = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
log = "0.4"